apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/contents/aws"
  labels:
    env: dev  
spec:
  selector:
    app: nodejs-backend