apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend