apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nodejs-backend
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nodejs-backend
  newTag: abcdefg
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/react-frontend
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/react-frontend
  newTag: abcdefg
- name: 838688157549.dkr.ecr.ap-northeast-2.amazonaws.com/nodejs-backend
  newName: 838688157549.dkr.ecr.ap-northeast-2.amazonaws.com/nodejs-backend
  newTag: 32b25671
- name: 838688157549.dkr.ecr.ap-northeast-2.amazonaws.com/react-frontend
  newName: 838688157549.dkr.ecr.ap-northeast-2.amazonaws.com/react-frontend
  newTag: e622594a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
- back-service-patch.yaml
- back-deployment-patch.yaml
