apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/react-frontend
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/react-frontend
  newTag: abcdefg
resources:
- ../../base
patches:
- ../../front-deployment-patch.yaml
- ../../front-service-patch.yaml