apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30