---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
        - name: backend-app
          image: 838688157549.dkr.ecr.ap-northeast-2.amazonaws.com/nodejs-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000